CREATE TABLE SILVER_HOTEL_BOOKING
(
booking_id VARCHAR,
hotel_id VARCHAR,
hotel_city VARCHAR,
customer_id VARCHAR,
customer_name VARCHAR,
customer_email VARCHAR,
check_in_date DATE,
check_out_date DATE,
room_type VARCHAR,
num_guests INTEGER,
total_amount FLOAT,
currency VARCHAR,
booking_status VARCHAR
);

SELECT * FROM BRONZE_HOTEL_BOOKING;

SELECT CUSTOMER_EMAIL FROM BRONZE_HOTEL_BOOKING
WHERE NOT (CUSTOMER_EMAIL LIKE '%@%.%')
 OR CUSTOMER_EMAIL IS NULL;

 SELECT TOTAL_AMOUNT FROM BRONZE_HOTEL_BOOKING
 WHERE TRY_TO_NUMBER(TOTAL_AMOUNT)<0;

 SELECT 
 CHECK_IN_DATE, CHECK_OUT_DATE 
 FROM 
 BRONZE_HOTEL_BOOKING
 WHERE TRY_TO_DATE(CHECK_OUT_DATE) < TRY_TO_DATE(CHECK_IN_DATE);

 
 SELECT 
  COALESCE(TRY_TO_DATE(CHECK_IN_DATE, 'MM/DD/YYYY'), TRY_TO_DATE(CHECK_IN_DATE, 'DD-MM-YYYY')) AS CHECK_IN_DATE,
  COALESCE(TRY_TO_DATE(CHECK_OUT_DATE, 'MM/DD/YYYY'), TRY_TO_DATE(CHECK_OUT_DATE, 'DD-MM-YYYY')) AS CHECK_OUT_DATE
FROM 
  HOTEL_DB.PUBLIC.BRONZE_HOTEL_BOOKING
WHERE 
  COALESCE(TRY_TO_DATE(CHECK_OUT_DATE, 'MM/DD/YYYY'), TRY_TO_DATE(CHECK_OUT_DATE, 'DD-MM-YYYY')) 
  < COALESCE(TRY_TO_DATE(CHECK_IN_DATE, 'MM/DD/YYYY'), TRY_TO_DATE(CHECK_IN_DATE, 'DD-MM-YYYY'));


INSERT INTO HOTEL_DB.PUBLIC.SILVER_HOTEL_BOOKING
SELECT
  BOOKING_ID,
  HOTEL_ID,
  INITCAP(TRIM(HOTEL_CITY)) AS HOTEL_CITY,
  CUSTOMER_ID,
  INITCAP(TRIM(CUSTOMER_NAME)) AS CUSTOMER_NAME,
  CASE
    WHEN CUSTOMER_EMAIL LIKE '%@%.%' THEN LOWER(TRIM(CUSTOMER_EMAIL))
    ELSE NULL
  END AS CUSTOMER_EMAIL,
  COALESCE(TRY_TO_DATE(NULLIF(CHECK_IN_DATE, 'MM/DD/YYYY')),    TRY_TO_DATE(NULLIF(CHECK_IN_DATE, 'DD-MM-YYYY'))) AS CHECK_IN_DATE,
  COALESCE(TRY_TO_DATE(NULLIF(CHECK_OUT_DATE, 'MM/DD/YYYY')), TRY_TO_DATE(NULLIF(CHECK_OUT_DATE, 'DD-MM-YYYY'))) AS CHECK_OUT_DATE,
  ROOM_TYPE,
  TRY_TO_NUMBER(NUM_GUESTS) AS NUM_GUESTS,
  ABS(TRY_TO_NUMBER(TOTAL_AMOUNT)) AS TOTAL_AMOUNT,
  CURRENCY,
  CASE 
    WHEN LOWER(BOOKING_STATUS)IN ('confirmeed', 'confirmeeed', 'confirmd') THEN 'Confirmed'
  ELSE BOOKING_STATUS
  END AS BOOKING_STATUS
FROM HOTEL_DB.PUBLIC.BRONZE_HOTEL_BOOKING
where 
    TRY_TO_DATE(CHECK_IN_DATE) IS NOT NULL
    AND TRY_TO_DATE(CHECK_OUT_DATE) IS NOT NULL
    AND TRY_TO_DATE(CHECK_OUT_DATE)>= TRY_TO_DATE(CHECK_IN_DATE);


SELECT * FROM SILVER_HOTEL_BOOKING;


